name: 'Redis Build Action'
description: 'Composite GitHub action for building Redis projects'
inputs:
  release:
    description: "True if this build is part of a release"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'zulu'

    - uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle') }}-${{ hashFiles('**/gradle.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Aggregate Jacoco report
      run: |
        ./gradlew -Prelease=${{ inputs.release }} aggregateJacocoReport -S
      shell: bash

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2